### ISSUE TITLE
Boss Kill Award Values Broken

### ISSUE THREAD

**Issue by oarzik** [lantisnt/ClassicLootManager#607]
**Describe the bug**
Our guild is on classic era, just noting that this bug is happening in the hopes of it being fixed.
We've tested this in both ZG & Naxx so far - boss kill award values are not awarded upon killing a boss in the raid when the raid is started, when this used to work.

**To Reproduce**
1. Enter the instance of the raid being done
2. Create a raid and ensure boss kill award values are set up & the checkbox is ticked
3. Start the raid
4. Kill a boss
5. Notice that no DKP popup appeared as the value was not awarded

**Expected behavior**
DKP popup should show upon boss kill and award DKP value for killin such boss

**AddOn and Game Version:**
 - Classic era, CLM version 5.3.1

**Comment by lantisnt** [comment]
Just to confirm: it's Classic Era not SoD or SoM?

**Comment by paradoxguild** [comment]
Sorry for the delay - indeed, Classic Era. Still going strong - full 40 mans running DKP via this addon.

**Comment by lantisnt** [comment]
Can you paste your settings of the Boss Kill Awards for ZG and default slot values?

There were some recent changes that might have led to the values being reset due to how difficulty IDs have changed

**Comment by paradoxguild** [comment]
For ZG the award values are 2 for every boss, 6 for hakkar, 5 for EOM.

For default slot values, everything is:
- Base: 5
- Small: 5
- Medium: 10
- Large: 20
- Max: 10000

![image](https://github.com/user-attachments/assets/720afb71-3125-4712-af26-1b7978853a1a)
These are the settings that I have when I create and start a raid, while I am in the instance.

**Comment by lantisnt** [comment]
default values are in configuration -> roster
the boss kill values are in the configuration -> roster -> boss kill (dropdown)
and then you need to scroll to ZG

**Comment by paradoxguild** [comment]
Yep.

> For ZG the award values are 2 for every boss, 6 for hakkar, 5 for EOM.

![image](https://github.com/user-attachments/assets/ea5f496b-5ae9-4a03-846e-4cec4fa24c3c)
![image](https://github.com/user-attachments/assets/5b290960-ed23-4d97-a322-5d664f58529c)

**Comment by paradoxguild** [comment]
The value for defaults for bonuses are as listed:

![image](https://github.com/user-attachments/assets/30a48fdf-d532-472f-84ed-449bca1e6e6b)

**Comment by lantisnt** [comment]
Can you do 
`/dump GetInstanceInfo()`
When in zg next time and post output?

**Comment by paradoxguild** [comment]
Can do. Unable to tonight/tomorrow but a guildy will be running one and screenshotting. Will follow up later tonight/tomorrow!

**Comment by paradoxguild** [comment]
![image](https://github.com/user-attachments/assets/3fbc87bd-2d21-4f05-890d-390212ea9630)
![image](https://github.com/user-attachments/assets/5df85c31-a389-45e7-b7d2-06c2ff0ac76a)

**Comment by lantisnt** [comment]
I see no issues in the code. Is this problem specific to ZG only?

**Comment by lantisnt** [comment]
I will need to see MLs logs set to level Info of a kill

**Comment by lantisnt** [comment]
@paradoxguild any updates on info on this one? Did it work or you Got the requested info for me?

**Comment by lantisnt** [comment]
Please verify if `v5.4.0` has it fixed
